[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
    'cd server && npm ci',
    'cd client && npm ci'
]

[phases.build]
cmds = [
    'cd client && npm run build'
]

[start]
cmd = 'cd server && npm start' 