[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
    'cd server && npm ci --only=production',
    'cd client && npm ci'
]

[phases.build]
cmds = [
    'cd client && npm run build'
]

[start]
cmd = 'cd server && npm start' 